from random import choice
import time

sent = choice([
    "The sun slowly rose.",
    "The wind blew softly.",
    "The surface of the lake sparkled.",
    "The birds were singing.",
    "The trees cast long shadows.",
    "The clouds drifted slowly.",
    "The stream flowed quietly.",
    "The meadow was full of flowers.",
    "The mountains were covered in mist.",
    "The sunlight warmed the landscape.",
    "The moon shone faintly.",
    "The stars were shining brightly.",
    "The wind moved the grass.",
    "A dog barked in the distance.",
    "The city woke up slowly.",
    "The waves of the sea crashed.",
    "The sand was warm.",
    "Seagulls flew along the shore.",
    "The leaves rustled in the trees.",
    "The sunbeams shone through.",
    "The fog slowly lifted.",
    "The river murmured quietly.",
    "The meadow smelled fresh.",
    "Birds circled in the sky.",
    "The sunset painted everything red.",
    "The wind blew cold.",
    "The snow fell slowly.",
    "The ice cracked under your feet.",
    "The clouds darkened.",
    "The storm was approaching.",
    "The landscape became silent.",
    "The sunbeams were blinding.",
    "The leaves began to fall.",
    "The tree trunks reached high.",
    "Bees buzzed in the meadow.",
    "The stones in the stream sparkled.",
    "Light glowed behind the mountains.",
    "The wind stirred up dust.",
    "The sunlight was golden.",
    "The birds suddenly flew away.",
    "The water of the lake was clear.",
    "Shadows hid between the trees.",
    "The meadow was full of life.",
    "The clouds slowly parted.",
    "The sun came out again.",
    "The wind shook the branches.",
    "The landscape was peaceful.",
    "The river flowed faster.",
    "The stones were cold.",
    "The grass was soft.",
    "The sunset was beautiful.",
    "The moonlight shone silver.",
    "The stars slowly appeared.",
    "The wind calmed down.",
    "A light flashed in the distance.",
    "The birds returned.",
    "The tree leaves were thick.",
    "Silence filled the meadow.",
    "The lakeshore was calm.",
    "The sunbeams danced.",
    "The wind swept across the land.",
    "The clouds swirled.",
    "The mountains cast shadows.",
    "The stream water was cold.",
    "The meadow was colorful.",
    "Light filtered through the trees.",
    "The sun slowly disappeared.",
    "The moon climbed into the sky.",
    "The stars were shining.",
    "The wind rose again.",
    "The land fell into darkness.",
    "The fog returned.",
    "The birds went silent.",
    "The lake surface became still.",
    "The meadow was deserted.",
    "The shadows of the trees grew long.",
    "The sunlight vanished.",
    "The wind struck cold.",
    "The clouds gathered.",
    "The storm broke out.",
    "The land trembled.",
    "The stream grew louder.",
    "The mountains echoed.",
    "The meadow filled with noise.",
    "The birds were startled.",
    "The trees bent.",
    "The sun shone again.",
    "The wind stopped.",
    "The land became peaceful again.",
    "The lake surface rippled.",
    "The meadow filled with life again.",
    "The tree leaves glowed.",
    "The sunbeams broke through.",
    "The birds returned.",
    "The wind blew gently.",
    "The land became quiet again.",
    "I don't like McDonald's.",
    "I survived Monday again.",
    "Coffee is my lifeline.",
    "My cat is my boss.",
    "My fridge is louder than me.",
    "My neighbor's drill is my favorite music.",
    "The Wi-Fi is stronger than my motivation.",
    "The couch defeated me again.",
    "My laziness is world champion.",
    "Waking up is the enemy.",
    "Yesterday's plan is still just a plan.",
    "I count pizza as a sport.",
    "Running is only good when it doesn't include running.",
    "My cat looks at me judgmentally.",
    "My dog is smarter than me.",
    "The mirror wasn't kind today.",
    "My fridge is empty but my soul is full.",
    "My neighbor is drilling again.",
    "The wind blew away my mood.",
    "Sunlight is too bright for me.",
    "The coffee is gone, and so am I.",
    "The chair creaks, not me.",
    "My phone charger always disappears.",
    "My sock's pair never shows up.",
    "Yesterday was faster than today.",
    "Chocolate is always a good idea.",
    "The snooze button is my best friend.",
    "Monday is too long.",
    "Friday is too short.",
    "Saturday goes by too fast.",
    "Sunday is too sleepy.",
    "My pillow holds me hostage.",
    "My blanket won't let me go.",
    "My motivation is on vacation.",
    "My thoughts are resting.",
    "A day without coffee is not a day.",
    "The chair is more comfortable than it should be.",
    "The fridge door is too loud.",
    "My shoes are too far away.",
    "Getting up is too hard.",
    "The day started too early.",
    "Yesterday was too much.",
    "Today is too little.",
    "Tomorrow will fix it.",
    "My cat looks down on me.",
    "My dog looks up to me.",
    "The mirror laughs at me.",
    "The chair squeaks again.",
    "The couch is calling me.",
    "The fridge tempts me.",
    "The chocolate smiles at me.",
    "The pizza winks at me.",
    "Cola is bubbly happiness.",
    "Chips crunch loudly.",
    "The wind blows away my worries.",
    "The sunlight blinds me.",
    "The moon winks at me.",
    "The stars judge me.",
    "My neighbor is louder than necessary.",
    "The radio sings off-key.",
    "My phone is too smart.",
    "My laptop is too warm.",
    "The keyboard is too loud.",
    "The chair is too comfortable.",
    "The bag is too heavy.",
    "The coat is too warm.",
    "The shoes are too tight.",
    "The socks are too loose.",
    "The pants are too loud.",
    "The shirt is too soft.",
    "My hair is too independent.",
    "My eyes are too sleepy.",
    "My ears are too sensitive.",
    "My hands are too cold.",
    "My legs are too lazy.",
    "My thoughts are too loud.",
    "My head is too empty.",
    "My heart beats too fast.",
    "My soul is too tired.",
    "My humor is too dry.",
    "My jokes are too bad.",
    "My laughter is too loud.",
    "The silence is suspicious.",
    "The sun is too bright.",
    "The moon is too pale.",
    "The star is too far.",
    "The world is too big.",
    "The room is too small.",
    "The couch is too comfortable.",
    "The fridge is too empty.",
    "My wallet is too light.",
    "My head is too heavy.",
    "The day is too long.",
    "The week is too fast.",
    "The month is too short.",
    "My humor is too weird.",
    "My mood is too unstable.",
    "The world is too funny."
])

input(sent)

start = time.time()
answer = input("Type the sentence!")
stop = time.time()

if answer == sent:
    print("Correct sentence!")
    elapsed = stop - start
    print(f"Elapsed time: {elapsed:.2f} seconds.")
    print(f"{elapsed:.2f}/{len(sent)} = {elapsed/len(sent):.2f} seconds/character.")
elif answer == "I don't like McDonald's.":
    print("Easter egg!")
    print("Correct sentence!")
    elapsed = stop - start
    print(f"Elapsed time: {elapsed:.2f} seconds.")
else:
    print("Incorrect sentence!")
    elapsed = stop - start
    print(f"Elapsed time: {elapsed:.2f} seconds.")
