from random import choice
import time
print("Made by Timot")

gep = choice([
    "A nap lassan felkelt.",
    "A szél halkan fújt.",
    "A tó felszíne csillogott.",
    "A madarak énekeltek.",
    "A fák árnyékot vetettek.",
    "A felhők lassan úsztak.",
    "A patak csendesen folyt.",
    "A mező tele volt virággal.",
    "A hegyek ködbe burkolóztak.",
    "A napfény melegítette a tájat.",
    "A hold halványan ragyogott.",
    "A csillagok fényesen égtek.",
    "A szél megmozgatta a füvet.",
    "A távolban kutya ugatott.",
    "A város lassan ébredt.",
    "A tenger hullámai csapkodtak.",
    "A homok meleg volt.",
    "A parton sirályok repültek.",
    "A fák lombjai zizegtek.",
    "A nap sugarai átsütöttek.",
    "A köd lassan felszállt.",
    "A folyó halkan csobogott.",
    "A rét illata friss volt.",
    "A madarak köröztek az égen.",
    "A naplemente vörösre festett mindent.",
    "A szél hidegen fújt.",
    "A hó lassan hullott.",
    "A jég ropogott a lábad alatt.",
    "A felhők sötétedtek.",
    "A vihar közeledett.",
    "A táj elcsendesedett.",
    "A nap sugarai vakítottak.",
    "A levelek hullani kezdtek.",
    "A fák törzsei magasra nyúltak.",
    "A mezőn méhek zümmögtek.",
    "A patak kövei csillogtak.",
    "A hegyek mögött fény derengett.",
    "A szél port kavart.",
    "A napfény aranyszínű volt.",
    "A madarak hirtelen elrepültek.",
    "A tó vize átlátszó volt.",
    "A fák között árnyék lapult.",
    "A rét tele volt élettel.",
    "A felhők lassan szétnyíltak.",
    "A nap újra kisütött.",
    "A szél megrázta az ágakat.",
    "A táj békés volt.",
    "A folyó gyorsabban folyt.",
    "A kövek hidegek voltak.",
    "A fű puha volt.",
    "A naplemente gyönyörű volt.",
    "A holdfény ezüstösen ragyogott.",
    "A csillagok lassan felbukkantak.",
    "A szél elcsendesedett.",
    "A távolban fény villant.",
    "A madarak visszatértek.",
    "A fák lombjai sűrűek voltak.",
    "A mezőn csend honolt.",
    "A tó partja nyugodt volt.",
    "A nap sugarai táncoltak.",
    "A szél végigsöpört a tájon.",
    "A felhők gomolyogtak.",
    "A hegyek árnyékot vetettek.",
    "A patak vize hideg volt.",
    "A rét színes volt.",
    "A fák között fény szűrődött be.",
    "A nap lassan eltűnt.",
    "A hold felkúszott az égre.",
    "A csillagok ragyogtak.",
    "A szél újra feltámadt.",
    "A táj sötétbe borult.",
    "A köd visszatért.",
    "A madarak elhallgattak.",
    "A tó felszíne elsimult.",
    "A mező kihalt volt.",
    "A fák árnyai megnyúltak.",
    "A napfény eltűnt.",
    "A szél hidegen csapott le.",
    "A felhők összegyűltek.",
    "A vihar kitört.",
    "A táj megremegett.",
    "A patak hangosabb lett.",
    "A hegyek visszhangoztak.",
    "A rét megtelt zajjal.",
    "A madarak felriadtak.",
    "A fák meghajoltak.",
    "A nap újra felragyogott.",
    "A szél elült.",
    "A táj újra békés lett.",
    "A tó felszíne hullámzott.",
    "A mező újra élettel telt meg.",
    "A fák lombjai fénylettek.",
    "A nap sugarai áttörtek.",
    "A madarak visszatértek.",
    "A szél lágyan fújt.",
    "A táj újra csendes lett.",
    "Nem szeretem a mekit.",
    "Ma megint túléltem a hétfőt.",
    "A kávé az életem mentőöve.",
    "A macskám a főnököm.",
    "A hűtőm hangosabb mint én.",
    "A szomszéd flexe a kedvenc zeném.",
    "A wifi erősebb mint a motivációm.",
    "A kanapé ma is legyőzött.",
    "A lustaságom világbajnok.",
    "A reggeli ébredés ellenség.",
    "A tegnapi terv ma is terv.",
    "A pizzát sportnak számítom.",
    "A futás csak akkor jó ha nincs benne futás.",
    "A macskám ítélkezőn néz rám.",
    "A kutyám okosabb nálam.",
    "A tükör ma sem volt kedves.",
    "A hűtő üres, de a lelkem tele.",
    "A szomszéd megint fúr.",
    "A szél elvitte a kedvem.",
    "A napfény túl fényes nekem.",
    "A kávé elfogyott, én is.",
    "A szék recseg, nem én.",
    "A telefon töltője mindig eltűnik.",
    "A zoknim párja sosem kerül elő.",
    "A tegnap gyorsabb volt mint ma.",
    "A csoki mindig jó ötlet.",
    "A szundi gomb a legjobb barátom.",
    "A hétfő túl hosszú.",
    "A péntek túl rövid.",
    "A szombat túl gyors.",
    "A vasárnap túl álmos.",
    "A párnám visszatart.",
    "A takaró fogva tart.",
    "A motivációm szabadságon van.",
    "A gondolataim pihennek.",
    "A kávé nélküli nap nem nap.",
    "A szék kényelmesebb mint kéne.",
    "A hűtő ajtaja túl hangos.",
    "A cipőm túl messze van.",
    "A felkelés túl nehéz.",
    "A nap túl korán kezdődött.",
    "A tegnap túl sok volt.",
    "A ma túl kevés.",
    "A holnap majd megoldja.",
    "A macskám lenéz.",
    "A kutyám felnéz.",
    "A tükör kinevet.",
    "A szék megnyikorog.",
    "A kanapé hívogat.",
    "A hűtő csábít.",
    "A csoki rám mosolyog.",
    "A pizza rám kacsint.",
    "A kóla buborékos öröm.",
    "A chips hangosan ropog.",
    "A szél kifújja a gondjaim.",
    "A napfény megvakít.",
    "A hold rám kacsint.",
    "A csillagok ítélkeznek.",
    "A szomszéd hangosabb mint kéne.",
    "A rádió hamisan énekel.",
    "A telefon túl okos.",
    "A laptop túl meleg.",
    "A billentyűzet túl hangos.",
    "A szék túl kényelmes.",
    "A táska túl nehéz.",
    "A kabát túl meleg.",
    "A cipő túl szoros.",
    "A zokni túl laza.",
    "A nadrág túl hangos.",
    "A póló túl puha.",
    "A hajam túl önálló.",
    "A szemem túl álmos.",
    "A fülem túl érzékeny.",
    "A kezem túl hideg.",
    "A lábam túl lusta.",
    "A gondolataim túl hangosak.",
    "A fejem túl üres.",
    "A szívem túl gyors.",
    "A lelkem túl fáradt.",
    "A humorom túl száraz.",
    "A poénjaim túl rosszak.",
    "A nevetésem túl hangos.",
    "A csend túl gyanús.",
    "A nap túl fényes.",
    "A hold túl sápadt.",
    "A csillag túl messze.",
    "A világ túl nagy.",
    "A szoba túl kicsi.",
    "A kanapé túl kényelmes.",
    "A hűtő túl üres.",
    "A pénztárcám túl könnyű.",
    "A fejem túl nehéz.",
    "A nap túl hosszú.",
    "A hét túl gyors.",
    "A hónap túl rövid.",
    "A humorom túl fura.",
    "A kedvem túl ingadozó.",
    "A világ túl vicces.",
    "A nap ma is túl fényes volt.",
    "A szél úgy döntött, hogy ma hangos lesz.",
    "A macskám megint elfoglalta a székem.",
    "A kávém gyorsabban fogy, mint a türelmem.",
    "A hűtőm furcsa hangot adott.",
    "A cipőm ma is ellenem dolgozott.",
    "A kanapé hívogatott egész nap.",
    "A szomszéd fúrója új rekordot döntött.",
    "A naplemente rózsaszínre festette az eget.",
    "A felhők ma is összeesküdtek ellenem.",
    "A tükör nem volt kedves hozzám.",
    "A szék megint recsegett alattam.",
    "A laptopom túl meleg lett.",
    "A telefonom túl okosnak hiszi magát.",
    "A csoki rám mosolygott a polcról.",
    "A pizza illata elcsábított.",
    "A chips hangosan ropogott.",
    "A kóla buborékai felvidítottak.",
    "A szél elvitte a gondolataimat.",
    "A hold ma különösen fényes volt.",
    "A csillagok ma is ítélkeztek.",
    "A szoba túl csendes volt.",
    "A világ túl hangos volt.",
    "A párnám nem engedett felkelni.",
    "A takaróm fogva tartott.",
    "A motivációm eltűnt valahol.",
    "A gondolataim szabadságot vettek ki.",
    "A nap túl hosszúra sikerült.",
    "A hét túl gyorsan telt.",
    "A hónap túl rövid volt.",
    "A humorom ma is fura volt.",
    "A kedvem ingadozott, mint a wifi.",
    "A villamos megint késett.",
    "A busz pont akkor ment el, amikor odaértem.",
    "A napfény arcon csapott.",
    "A szél összekócolta a hajam.",
    "A kabátom túl meleg volt.",
    "A nadrágom túl szoros lett.",
    "A pólóm túl puha volt.",
    "A hajam önálló életet élt.",
    "A szemem túl álmos volt.",
    "A kezem túl hideg volt.",
    "A lábam túl lusta volt.",
    "A fejem túl üres volt.",
    "A szívem túl gyorsan vert.",
    "A lelkem túl fáradt volt.",
    "A humorom túl száraz volt.",
    "A poénjaim túl rosszak voltak.",
    "A csend túl gyanús volt.",
    "A világ túl nagy volt.",
    "A szoba túl kicsi volt.",
    "A kanapé túl kényelmes volt.",
    "A hűtő túl üres volt.",
    "A pénztárcám túl könnyű lett.",
    "A nap túl korán kezdődött.",
    "A tegnap túl sok volt.",
    "A ma túl kevés volt.",
    "A holnap majd megoldja.",
    "A madarak túl hangosan énekeltek.",
    "A felhők furcsa alakot vettek fel.",
    "A patak hangja megnyugtatott.",
    "A hegyek mögött fény derengett.",
    "A rét illata friss volt.",
    "A tó felszíne sima volt.",
    "A fák lombjai susogtak.",
    "A mező tele volt élettel.",
    "A szél lágyan fújt.",
    "A táj békés volt.",
    "A hold ezüstösen ragyogott.",
    "A csillagok lassan felbukkantak.",
    "A köd visszatért.",
    "A távolban fény villant.",
    "A madarak hirtelen elrepültek.",
    "A nap sugarai áttörtek a felhőkön.",
    "A szél végigsöpört a tájon.",
    "A felhők gomolyogtak.",
    "A hegyek árnyékot vetettek.",
    "A patak vize hideg volt.",
    "A rét színes volt.",
    "A fák között fény szűrődött be.",
    "A nap lassan eltűnt.",
    "A hold felkúszott az égre.",
    "A táj sötétbe borult.",
    "A mező kihalt volt.",
    "A fák árnyai megnyúltak.",
    "A szél hidegen csapott le.",
    "A vihar közeledett.",
    "A táj megremegett.",
    "A patak hangosabb lett.",
    "A hegyek visszhangoztak.",
    "A rét megtelt zajjal.",
    "A madarak felriadtak.",
    "A fák meghajoltak.",
    "A nap újra felragyogott.",
    "A szél elült.",
    "A táj újra békés lett."
])

input(gep)

start = time.time()
valasz = input("Írd le a mondatot!")
stop = time.time()

if valasz == gep:
    print("Helyes a mondat!")
    elapsed = stop - start
    print(f"Eltelt idő: {elapsed:.2f} másodperc.")
    print(f"{elapsed:.2f}/{len(gep)} = {elapsed/len(gep):.2f} másodperc/karakter.")
elif valasz == "Nem szeretem a mekit.":
    print("Easter egg!")
    print("Helyes a mondat!")
    elapsed = stop - start
    print(f"Eltelt idő: {elapsed:.2f} másodperc.")
else:
    print("Helytelen a mondat!")
    elapsed = stop - start
    print(f"Eltelt idő: {elapsed:.2f} másodperc.")
